#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
KIT_DIR="${SCRIPT_DIR}/sbx-sshd-v4"
REMOTE_SSH_FILE="${PWD}/.sbx_remote_ssh"
SBX_INTERNAL_SSH_PORT=2222
SBX_SSH_USER="${SBX_SSH_USER:-agent}"

usage() {
  echo "Usage: $0 SANDBOX_NAME" >&2
}

resolve_public_key_path() {
  if [[ -n "${PUBLIC_KEY_PATH:-}" ]]; then
    printf '%s\n' "${PUBLIC_KEY_PATH}"
    return 0
  fi

  local candidate
  for candidate in "${HOME}/.ssh/id_ed25519.pub" "${HOME}/.ssh/id_rsa.pub"; do
    if [[ -f "${candidate}" ]]; then
      printf '%s\n' "${candidate}"
      return 0
    fi
  done

  echo "No public key found. Set PUBLIC_KEY_PATH to your *.pub file." >&2
  return 1
}

choose_random_port() {
  local attempt port

  for attempt in $(seq 1 100); do
    port="$((12000 + RANDOM % 1001))"
    if command -v lsof >/dev/null 2>&1; then
      if lsof -nP -iTCP:"${port}" -sTCP:LISTEN >/dev/null 2>&1; then
        continue
      fi
    fi

    printf '%s\n' "${port}"
    return 0
  done

  echo "Failed to choose an unused host port in 12000-13000." >&2
  return 1
}

ensure_sandbox_running() {
  local sandbox_name="$1"

  if ! sbx exec "${sandbox_name}" true >/dev/null; then
    echo "Sandbox could not be started: ${sandbox_name}" >&2
    echo "Create it first with something like: sbx run -d shell --name ${sandbox_name} ." >&2
    return 1
  fi
}

kit_already_added() {
  local sandbox_name="$1"

  sbx exec "${sandbox_name}" sh -lc '
    test -f /home/agent/.sbx-sshd-v4-installed &&
    test -f /home/agent/.ssh/sshd_config &&
    command -v sshd >/dev/null 2>&1
  ' >/dev/null 2>&1
}

install_public_key() {
  local sandbox_name="$1"
  local public_key_path="$2"
  local sandbox_tmp_path="/tmp/sbx-authorized-key.pub"

  sbx cp "${public_key_path}" "${sandbox_name}:${sandbox_tmp_path}"
  sbx exec -u root "${sandbox_name}" sh -lc "
    set -eux
    install -d -m 700 -o agent -g agent /home/agent/.ssh
    install -m 600 -o agent -g agent ${sandbox_tmp_path} /home/agent/.ssh/authorized_keys
    rm -f ${sandbox_tmp_path}
    chown agent:agent /home/agent/.ssh/authorized_keys
    chmod 600 /home/agent/.ssh/authorized_keys
  "
}

restart_sandbox() {
  local sandbox_name="$1"

  sbx stop "${sandbox_name}" >/dev/null
  sbx exec "${sandbox_name}" true >/dev/null
}

write_remote_ssh_file() {
  local sandbox_name="$1"
  local ssh_port="$2"

  printf '# Generated by v4-include.sh\n' > "${REMOTE_SSH_FILE}"
  printf 'SBX_SANDBOX_NAME=%q\n' "${sandbox_name}" >> "${REMOTE_SSH_FILE}"
  printf 'SBX_SSH_PORT=%q\n' "${ssh_port}" >> "${REMOTE_SSH_FILE}"
  printf 'SBX_SSH_USER=%q\n' "${SBX_SSH_USER}" >> "${REMOTE_SSH_FILE}"
  printf 'SBX_INTERNAL_SSH_PORT=%q\n' "${SBX_INTERNAL_SSH_PORT}" >> "${REMOTE_SSH_FILE}"
}

main() {
  local sandbox_name public_key_path ssh_port

  if [[ $# -ne 1 ]]; then
    usage
    exit 1
  fi

  sandbox_name="$1"
  public_key_path="$(resolve_public_key_path)"
  ssh_port="$(choose_random_port)"

  ensure_sandbox_running "${sandbox_name}"

  if ! kit_already_added "${sandbox_name}"; then
    sbx kit add "${sandbox_name}" "${KIT_DIR}"
  fi

  install_public_key "${sandbox_name}" "${public_key_path}"
  restart_sandbox "${sandbox_name}"
  write_remote_ssh_file "${sandbox_name}" "${ssh_port}"

  echo "Configured sandbox: ${sandbox_name}"
  echo "Using public key: ${public_key_path}"
  echo "Wrote ${REMOTE_SSH_FILE} with SSH port ${ssh_port}"
}

main "$@"
